### ISSUE TITLE
figure_speed.png

### ISSUE THREAD

**Issue by lly456** [MuhammadMoinFaisal/YOLOv8_Segmentation_DeepSORT_Object_Tracking#1]
hello, 

https://github.com/MuhammadMoinFaisal/YOLOv8_Segmentation_DeepSORT_Object_Tracking/raw/main/ultralytics/figure_speed.png
can you upload the code which output the above figure _spped.png? I did not find it?

thank you.

**Comment by MuhammadMoinFaisal** [comment]
Hi @lly456 , this is the screen shot taken from the output video demo, if you follow the steps provided in the repo you will be able to get such output demo video

**Comment by lly456** [comment]
hi,
 I carried the steps in the readme.md, mainly the 'python predict.py model=yolov8x-seg.pt source="test1.mp4"' , and get the output of figure2.png, which did not display the speed, quantity and entering analysis. These are in the figure_sppeed.png.

thanks for your reply all the time.

**Comment by lly456** [comment]
@MuhammadMoinFaisal

**Comment by MuhammadMoinFaisal** [comment]
Ohh Sorry @lly456, these steps are explained in this video, Please check it and you are able to get the results as shown in the image. The who traffic counting and speed calculation code is explained in the video below.
https://www.youtube.com/watch?v=WhXWodX8fL0&t=1405s
and the speed calculation code file is available for our patreon supporters, with 5$ you can have acess to all the exclusive contents which we share there and also live chat support is provided as well.
Patreon Link:
https://www.patreon.com/user?u=86750182
Thank You

**Comment by lly456** [comment]
thanks for your help~
@MuhammadMoinFaisal
